# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed626da2e54c12d00c6a6ea968cbb72dcfcf2d7bebb73740a1d136928cbb5fb36603b7c5a204201e554ee8c4d965e7e4f27d96d084841e93947699f22a77cab4

test:
  secret_key_base: 29e1ebac904d27274fea7cf279e0069bdd273a353a627b6e48aeeeff2e72768535c169b91959ce5a7ff346a9108d37333e0108a3b1e447047ee7ce95937d9bbf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
